#ifndef TRANSPARENTSCROLLAREA_GLOBAL_H
#define TRANSPARENTSCROLLAREA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSPARENTSCROLLAREA_LIBRARY)
#  define TRANSPARENTSCROLLAREA_API Q_DECL_EXPORT
#else
#  define TRANSPARENTSCROLLAREA_API Q_DECL_IMPORT
#endif

#endif // TRANSPARENTSCROLLAREA_GLOBAL_H
