#ifndef NAVIGATIONLAYOUT_GLOBAL_H
#define NAVIGATIONLAYOUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NAVIGATIONLAYOUTWIDGET_LIBRARY)
#  define NAVIGATIONLAYOUT_API Q_DECL_EXPORT
#else
#  define NAVIGATIONLAYOUT_API Q_DECL_IMPORT
#endif

#endif // NAVIGATIONLAYOUT_GLOBAL_H
