#ifndef PARAMETERSWIDGETCOLLECTION_GLOBAL_H
#define PARAMETERSWIDGETCOLLECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PARAMETERSWIDGETCOLLECTION_LIBRARY)
#  define PARAMETERS_WIDGETS_API Q_DECL_EXPORT
#else
#  define PARAMETERS_WIDGETS_API Q_DECL_IMPORT
#endif

#endif // PARAMETERSWIDGETCOLLECTION_GLOBAL_H
