#ifndef NAVIGATIONWIDGETS_GLOBAL_H
#define NAVIGATIONWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NAVIGATIONWIDGETS_LIBRARY)
#  define NAVIGATIONWIDGETS_API Q_DECL_EXPORT
#else
#  define NAVIGATIONWIDGETS_API Q_DECL_IMPORT
#endif


#endif // NAVIGATIONWIDGETS_GLOBAL_H
